locales:
  tkl:
    name: Tokelauan Keyboards
    description: >-
      Mobile OS keyboards for the Tokelauan language from the Divvun group
      at UiT.
  en:
    name: Tokelauan Keyboards
    description: >-
      Mobile OS keyboards for the Tokelauan language from the Divvun group
      at UiT.
  nb:
    name: Tokelauan tastatur
    description: Mobiltastatur for Tokelauan fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
